// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKLIhu8ARc0mKNqE78TkT9Rvkr_8sTOk',
    appId: '1:641869113667:web:d8a6f5803e538a86a827f6',
    messagingSenderId: '641869113667',
    projectId: 'angeles-victor-9b',
    authDomain: 'angeles-victor-9b.firebaseapp.com',
    storageBucket: 'angeles-victor-9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUcHSEXb9EQlRlERCH-rqEeVMV0f1WwcA',
    appId: '1:641869113667:android:964a80350a48eff6a827f6',
    messagingSenderId: '641869113667',
    projectId: 'angeles-victor-9b',
    storageBucket: 'angeles-victor-9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWEHuvT3nV7Wg2tX-9sb93hht6LL4Nh_Y',
    appId: '1:641869113667:ios:6178363da9a227d5a827f6',
    messagingSenderId: '641869113667',
    projectId: 'angeles-victor-9b',
    storageBucket: 'angeles-victor-9b.appspot.com',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWEHuvT3nV7Wg2tX-9sb93hht6LL4Nh_Y',
    appId: '1:641869113667:ios:6178363da9a227d5a827f6',
    messagingSenderId: '641869113667',
    projectId: 'angeles-victor-9b',
    storageBucket: 'angeles-victor-9b.appspot.com',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCKLIhu8ARc0mKNqE78TkT9Rvkr_8sTOk',
    appId: '1:641869113667:web:c807f915bb47f953a827f6',
    messagingSenderId: '641869113667',
    projectId: 'angeles-victor-9b',
    authDomain: 'angeles-victor-9b.firebaseapp.com',
    storageBucket: 'angeles-victor-9b.appspot.com',
  );
}
